#!/usr/bin/env node
/**
 * Project Manager - Setup Script
 * 
 * Creates initial users and configures access.
 * Run: node scripts/setup.js
 * 
 * Options:
 *   --reset    Drop existing users and recreate them
 *   --env      Generate a .env.local template
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const SALT_ROUNDS = 12;

// ── User Schema (inline to avoid TS imports) ────────────────────────
const UserSchema = new mongoose.Schema(
  {
    username: { type: String, required: true, unique: true, trim: true, lowercase: true },
    name: { type: String, required: true, trim: true },
    password: { type: String, required: true },
    role: { type: String, enum: ['admin', 'member'], default: 'member' },
    isActive: { type: Boolean, default: true },
    lastLogin: { type: Date, default: null },
    failedAttempts: { type: Number, default: 0 },
    lockedUntil: { type: Date, default: null },
  },
  { timestamps: true }
);
const User = mongoose.model('User', UserSchema);

// ── Helpers ─────────────────────────────────────────────────────────
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

function generateSecret(len = 48) {
  return crypto.randomBytes(len).toString('base64url');
}

async function hashPassword(pw) {
  return bcrypt.hash(pw, SALT_ROUNDS);
}

// ── .env.local Generator ────────────────────────────────────────────
async function generateEnv() {
  const envPath = path.join(__dirname, '..', '.env.local');
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('.env.local already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('⏭️  Skipped .env.local generation.');
      return null;
    }
  }

  const mongoUri = (await ask('MongoDB URI (default: mongodb://localhost:27017/project-manager): ')).trim()
    || 'mongodb://localhost:27017/project-manager';

  const jwtSecret = generateSecret();

  const content = `# Project Manager - Environment Variables
# Generated by setup script on ${new Date().toISOString()}

# MongoDB Connection
MONGODB_URI=${mongoUri}

# JWT Secret (auto-generated, keep secret!)
JWT_SECRET=${jwtSecret}

# AWS S3 (optional - for file uploads)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
AWS_S3_BUCKET=project-manager-uploads
`;

  fs.writeFileSync(envPath, content, 'utf-8');
  console.log('✅ .env.local created successfully.');
  return mongoUri;
}

// ── User Creator ────────────────────────────────────────────────────
async function createUser(defaults = {}) {
  const username = ((await ask(`  Username (default: ${defaults.username || ''}): `)).trim()
    || defaults.username).toLowerCase();
  const name = (await ask(`  Display Name (default: ${defaults.name || username}): `)).trim()
    || defaults.name || username;
  const role = ((await ask(`  Role - admin/member (default: ${defaults.role || 'member'}): `)).trim()
    || defaults.role || 'member').toLowerCase();
  
  let password = '';
  while (!password || password.length < 4) {
    password = (await ask('  Password (min 4 chars): ')).trim();
    if (password.length < 4) console.log('  ⚠️  Password too short. Try again.');
  }

  const hashed = await hashPassword(password);

  const existing = await User.findOne({ username });
  if (existing) {
    existing.name = name;
    existing.password = hashed;
    existing.role = role;
    existing.isActive = true;
    existing.failedAttempts = 0;
    existing.lockedUntil = null;
    await existing.save();
    console.log(`  🔄 User "${username}" updated.`);
  } else {
    await User.create({ username, name, password: hashed, role });
    console.log(`  ✅ User "${username}" created.`);
  }

  return { username, name, role };
}

// ── Main ────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);
  const doReset = args.includes('--reset');
  const doEnv = args.includes('--env');

  console.log('\n🚀 Project Manager Setup\n' + '─'.repeat(40));

  // Step 1: Generate .env.local if requested
  let mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/project-manager';
  if (doEnv) {
    const uri = await generateEnv();
    if (uri) mongoUri = uri;
  }

  // Step 2: Connect to MongoDB
  console.log(`\n📦 Connecting to MongoDB...`);
  try {
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB.');
  } catch (err) {
    console.error('❌ Failed to connect to MongoDB:', err.message);
    console.log('\nMake sure MongoDB is running and the URI is correct.');
    console.log('Run with --env to generate a .env.local file first.\n');
    process.exit(1);
  }

  // Step 3: Reset users if requested
  if (doReset) {
    const confirm = await ask('\n⚠️  This will DELETE all existing users. Continue? (y/N): ');
    if (confirm.toLowerCase() === 'y') {
      await User.deleteMany({});
      console.log('🗑️  All users deleted.');
    } else {
      console.log('⏭️  Skipped user reset.');
    }
  }

  // Step 4: Show existing users
  const existingUsers = await User.find({}, 'username name role isActive lastLogin');
  if (existingUsers.length > 0) {
    console.log(`\n📋 Existing Users (${existingUsers.length}):`);
    existingUsers.forEach((u) => {
      const status = u.isActive ? '🟢' : '🔴';
      const login = u.lastLogin ? u.lastLogin.toLocaleDateString() : 'never';
      console.log(`   ${status} ${u.username} (${u.name}) — ${u.role} — last login: ${login}`);
    });
  } else {
    console.log('\n📋 No users found. Let\'s create some!');
  }

  // Step 5: Create users
  const createMore = existingUsers.length === 0 ? 'y'
    : (await ask('\nCreate/update users? (Y/n): ')).trim().toLowerCase() || 'y';

  if (createMore === 'y') {
    // Default admin
    console.log('\n👤 Admin User:');
    await createUser({ username: 'admin', name: 'Admin', role: 'admin' });

    let more = (await ask('\nCreate another user? (y/N): ')).trim().toLowerCase();
    while (more === 'y') {
      console.log('\n👤 New User:');
      await createUser({ role: 'member' });
      more = (await ask('\nCreate another user? (y/N): ')).trim().toLowerCase();
    }
  }

  // Step 6: Summary
  const finalUsers = await User.find({}, 'username name role isActive');
  console.log(`\n${'─'.repeat(40)}`);
  console.log('✅ Setup Complete!\n');
  console.log(`📋 Users (${finalUsers.length}):`);
  finalUsers.forEach((u) => {
    console.log(`   • ${u.username} (${u.name}) — ${u.role}`);
  });
  console.log(`\n🌐 Start the app: npm run dev`);
  console.log(`📍 Open: http://localhost:3000\n`);

  await mongoose.disconnect();
  rl.close();
}

main().catch((err) => {
  console.error('❌ Setup failed:', err);
  process.exit(1);
});
